#!/usr/bin/env python3
"""Comparative runner: Catala ↔ lawc ↔ lawref on the same cases.

Run from the repository root:

    python3 corpus/laws/kz/vred-ts/tools/catala/compare.py --emit      # generate tests/parity/*.lawtest from cases.json
    python3 corpus/laws/kz/vred-ts/tools/catala/compare.py --check     # generated files are up to date
    python3 corpus/laws/kz/vred-ts/tools/catala/compare.py --catala    # Catala against the cases.json expectations
    python3 corpus/laws/kz/vred-ts/tools/catala/compare.py --engines   # lawc + lawref on the same cases (private profile snapshot)
    python3 corpus/laws/kz/vred-ts/tools/catala/compare.py --property 200 --seed 1   # random cases: Python reference ↔ Catala ↔ lawc
    python3 corpus/laws/kz/vred-ts/tools/catala/compare.py --all       # emit-check + catala + engines

The expectations are cases.json (set by hand from the Rules text and the
calendar); the generated .lawtest files carry the same expectations, and the
common entry point `sh verify/ci/run_all.sh` runs them through both
evaluators as the `kz.corpus.vred_ts#catala-parity` family. Catala is
invoked via `clerk run ... --input <json> -F json`; an `Absent` output ⇔
NEITHER (the key is absent from the JSON).

Catala setup: `catala`/`clerk` 1.2.0 are looked up in PATH and in ~/.opam/*/bin.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import random
import shutil
import subprocess
import sys
import tempfile
from decimal import Decimal
from fractions import Fraction
from pathlib import Path

HERE = Path(__file__).resolve().parent
PACKAGE = HERE.parents[1]


def _repo_root(start: Path) -> Path:
    for path in [start, *start.parents]:
        if (path / "engines" / "checker").is_dir() and (path / "corpus" / "clir").is_dir():
            return path
    raise SystemExit("compare.py: checkout root not found")


ROOT = _repo_root(HERE)
CASES = HERE / "cases.json"
MODEL = HERE / "vred_ts.catala_en"
PARITY_DIR = PACKAGE / "tests" / "parity"
FAMILY = "kz.corpus.vred_ts#catala-parity"

CONTEXT_NO_CAL = """        context {
            decision_time @2026-09-01T12:00:00+05:00;
            knowledge_time @2026-09-01T12:00:00+05:00;
            legal_time @2026-09-01;
            timezone "Asia/Qyzylorda";
        }
"""
CONTEXT_CAL = """        context extends KZ_VRED_TS_DEADLINES {
            decision_time @2026-09-01T12:00:00+05:00;
            knowledge_time @2026-09-01T12:00:00+05:00;
            legal_time @2026-09-01;
            timezone "Asia/Qyzylorda";
            calendar "urn:kz:corpus:clir:official-calendar#snapshot-2026";
        }
"""
PROFILE = """context profile KZ_VRED_TS_DEADLINES {
    deadline_policy {
            start_count next_day;
            include_end true;
            roll next_working_day;
        }
}

"""
HEADER = """language "law.core" version "{version}";
package kz.corpus.vred_ts version "0.1.0";
namespace "urn:kz:corpus:clir:vred-ts";

// GENERATED by compare.py --emit from tools/catala/cases.json — do not edit by hand.
// Expectations are the cases.json reference set (per the Rules text and the
// 2026 calendar), shared with the Catala model tools/catala/vred_ts.catala_en.

"""

E = {"ts": 'entity_ref("urn:parity:vred:ts-1")', "r": 'entity_ref("urn:parity:vred:raschet-1")',
     "d": 'entity_ref("urn:parity:vred:detal-1")', "p": 'entity_ref("urn:parity:vred:poterpevshiy-1")',
     "s": 'entity_ref("urn:parity:vred:strakhovshchik-1")', "o": 'entity_ref("urn:parity:vred:otchet-1")'}


def money(value) -> str:
    text = format(Decimal(str(value)), "f")
    return f"{text} KZT"


def load_cases() -> dict:
    return json.loads(CASES.read_text(encoding="utf-8"))


def load_calendar(cases: dict) -> dict:
    data = json.loads((ROOT / cases["calendar_dataset"]).read_text(encoding="utf-8"))
    return {"nachalo": data["valid"]["start"], "konets_isklyuchitelno": data["valid"]["endExclusive"],
            "nerabochie_dni": [o["date"] for o in data["overrides"] if not o["working"]]}


# --------------------------------------------------------------------------
# Independent Python reference (for --property): fractions and its own calendar.
# --------------------------------------------------------------------------
class Reference:
    def __init__(self, calendar: dict):
        self.start = dt.date.fromisoformat(calendar["nachalo"])
        self.end = dt.date.fromisoformat(calendar["konets_isklyuchitelno"])
        self.holidays = {dt.date.fromisoformat(d) for d in calendar["nerabochie_dni"]}

    def working(self, day: dt.date) -> bool:
        return day.weekday() < 5 and day not in self.holidays

    def nth_working_after(self, day: dt.date, n: int):
        if not (self.start <= day < self.end):
            return None
        cur, left = day, n
        while left > 0:
            cur += dt.timedelta(days=1)
            if not (self.start <= cur < self.end):
                return None
            if self.working(cur):
                left -= 1
        return cur.isoformat()

    @staticmethod
    def gibel(i: dict) -> dict:
        costs, market = i.get("ozhidaemye_raskhody"), i.get("rynochnaya_stoimost")
        net = True if (costs is not None and market is not None
                       and Fraction(costs) > Fraction(market) * Fraction(4, 5)) else None
        unich = True if (i.get("tekhnicheski_nevozmozhno") or net) else None
        vyplata = None
        if unich and market is not None:
            per = i.get("ostatki_peredany")
            if per is True:
                vyplata = market
            elif per is False and i.get("stoimost_godnykh_ostatkov") is not None:
                vyplata = market - i["stoimost_godnykh_ostatkov"]
        return {"netselesoobrazno": net, "unichtozheno": unich, "vyplata": vyplata}

    @staticmethod
    def detal(i: dict) -> dict:
        km = i.get("srednegodovoy_probeg_km")
        tselaya = i.get("ranee_ne_povrezhdalas") and i.get("ne_podvergalas_remontu")
        bez = None
        if i.get("podlezhit_zamene") and tselaya and km is not None:
            if i.get("vladelets") == "FizicheskoeLitso" and i.get("ne_podlezhit_tekhosmotru") and km <= 15000:
                bez = True
            if i.get("vladelets") == "YuridicheskoeLitso" and i.get("na_garantiynom_obsluzhivanii") and km <= 20000:
                bez = True
        if bez:
            stoimost = i.get("stoimost_novoy")
        else:
            stoimost = i.get("stoimost_s_uchetom_iznosa")
        return {"bez_iznosa": bez, "stoimost": stoimost}

    @staticmethod
    def vybor(i: dict) -> dict:
        n = i.get("predlozheno")
        return {"obespechen": None if n is None else n >= 2}

    def sroki(self, i: dict) -> dict:
        out = {k: None for k in ("predel_otmetki", "predel_otveta", "predel_otcheta", "otchet_ne_v_srok", "pravo_na_vyplatu")}
        if i.get("uproshchennoe_oformlenie"):
            return out
        if i.get("otchet_poluchen"):
            out["predel_otmetki"] = self.nth_working_after(dt.date.fromisoformat(i["otchet_poluchen"]), 3)
        if i.get("otmetka_nesoglasiya_poluchena"):
            out["predel_otveta"] = self.nth_working_after(dt.date.fromisoformat(i["otmetka_nesoglasiya_poluchena"]), 3)
        if i.get("osmotr_osushchestvlen"):
            out["predel_otcheta"] = self.nth_working_after(dt.date.fromisoformat(i["osmotr_osushchestvlen"]), 5)
        due = out["predel_otcheta"]
        if due:
            late = i.get("otchet_poluchen") and i["otchet_poluchen"] > due
            never = (i.get("otchet_predostavlen") is False and i.get("den_rassmotreniya")
                     and i["den_rassmotreniya"] > due)
            if late or never:
                out["otchet_ne_v_srok"] = True
                out["pravo_na_vyplatu"] = True
        return out

    def compute(self, scope: str, inputs: dict) -> dict:
        return {"Gibel": self.gibel, "StoimostDetali": self.detal, "VyborOtsenshchikov": self.vybor,
                "SrokiPunkta3": self.sroki}[scope](inputs)


# --------------------------------------------------------------------------
# Generating a .lawtest from a case: the same inputs as facts, the same expectations.
# --------------------------------------------------------------------------
def truth_expect(pred: str, value) -> str:
    status = {None: "NEITHER", True: "TRUE_ONLY", False: "FALSE_ONLY"}[value]
    return f"    evaluate truth({pred});\n    expect truth_status == {status};\n"


def value_expect(var: str, typ: str, pred_tpl: str, value, render) -> str:
    """Numeric/date output: exactly one value and it matches, or none at all."""
    out = (f"    evaluate collect {var}: {typ} where {pred_tpl.format(v=var)};\n"
           f"    expect result_kind == COLLECTION;\n")
    if value is None:
        return out + "    expect collected_count(0);\n"
    return (out + "    expect collected_count(1);\n"
            + f"    evaluate truth({pred_tpl.format(v=render(value))});\n    expect truth_status == TRUE_ONLY;\n")


def lawtest_case(case: dict) -> tuple[str, bool]:
    """Returns (test text, needs_calendar)."""
    i, x, scope = case["inputs"], case["expected"], case["scope"]
    facts: list[str] = []
    checks = ""
    a = facts.append
    if scope == "Gibel":
        a(f"raschet_po_ts({E['r']}, {E['ts']})")
        if i.get("tekhnicheski_nevozmozhno"):
            a(f"vosstanovlenie_tekhnicheski_nevozmozhno({E['ts']})")
        if i.get("ozhidaemye_raskhody") is not None:
            a(f"ozhidaemye_raskhody_na_vosstanovlenie({E['ts']}, {money(i['ozhidaemye_raskhody'])})")
        if i.get("rynochnaya_stoimost") is not None:
            a(f"rynochnaya_stoimost_na_datu_otcheta({E['ts']}, {money(i['rynochnaya_stoimost'])})")
        if i.get("ostatki_peredany") is True:
            a(f"ostatki_peredany_v_sobstvennost_strakhovshchika({E['r']})")
        elif i.get("ostatki_peredany") is False:
            a(f"not ostatki_peredany_v_sobstvennost_strakhovshchika({E['r']})")
        if i.get("stoimost_godnykh_ostatkov") is not None:
            a(f"stoimost_godnykh_k_realizatsii_ostatkov({E['ts']}, {money(i['stoimost_godnykh_ostatkov'])})")
        checks += truth_expect(f"vosstanovlenie_ekonomicheski_netselesoobrazno({E['ts']})", x["netselesoobrazno"])
        checks += truth_expect(f"ts_schitaetsya_unichtozhennym({E['ts']})", x["unichtozheno"])
        checks += value_expect("amount", "Money", f"strakhovaya_vyplata_pri_gibeli({E['r']}, {{v}})", x["vyplata"], money)
    elif scope == "StoimostDetali":
        a(f"detal_ts({E['d']}, {E['ts']})")
        if i.get("podlezhit_zamene"):
            a(f"detal_podlezhit_zamene({E['d']})")
        if i.get("vladelets") == "FizicheskoeLitso":
            a(f"vladelets_fizicheskoe_litso({E['ts']})")
        if i.get("vladelets") == "YuridicheskoeLitso":
            a(f"vladelets_yuridicheskoe_litso({E['ts']})")
        if i.get("ne_podlezhit_tekhosmotru"):
            a(f"ne_podlezhit_obyazatelnomu_tekhosmotru({E['ts']})")
        if i.get("na_garantiynom_obsluzhivanii"):
            a(f"nakhoditsya_na_garantiynom_obsluzhivanii({E['ts']})")
        if i.get("srednegodovoy_probeg_km") is not None:
            a(f"srednegodovoy_probeg({E['ts']}, {i['srednegodovoy_probeg_km']} km)")
        if i.get("ranee_ne_povrezhdalas"):
            a(f"detal_ranee_ne_povrezhdalas({E['d']})")
        if i.get("ne_podvergalas_remontu"):
            a(f"detal_ne_podvergalas_remontu({E['d']})")
        if i.get("stoimost_novoy") is not None:
            a(f"rynochnaya_stoimost_novoy_detali({E['d']}, {money(i['stoimost_novoy'])})")
        if i.get("stoimost_s_uchetom_iznosa") is not None:
            a(f"stoimost_detali_s_uchetom_iznosa({E['d']}, {money(i['stoimost_s_uchetom_iznosa'])})")
        checks += truth_expect(f"detal_otsenivaetsya_bez_iznosa({E['d']})", x["bez_iznosa"])
        checks += value_expect("amount", "Money", f"stoimost_zamenyaemoy_detali({E['d']}, {{v}})", x["stoimost"], money)
    elif scope == "VyborOtsenshchikov":
        if i.get("predlozheno") is not None:
            a(f"predlozheno_otsenshchikov({E['r']}, {i['predlozheno']})")
        checks += truth_expect(f"vybor_otsenshchikov_obespechen({E['r']})", x["obespechen"])
    elif scope == "DopustimostOsmotra":
        names = {"dostup_besprepyatstvennyy": "dostup_k_ts_besprepyatstvennyy", "identifikatsiya_provodima": "identifikatsiya_ts_provodima",
                 "probeg_ustanovim": "probeg_po_odometru_ustanovim", "komplektnost_ustanovima": "komplektnost_ustanovima",
                 "perechen_defektov_ustanovim": "perechen_defektov_ustanovim", "fotosemka_provodima": "fotosemka_povrezhdeniy_provodima",
                 "priznaki_remontov_ustanovimy": "priznaki_prezhnikh_remontov_ustanovimy"}
        for key, pred in names.items():
            if i.get(key):
                a(f"{pred}({E['r']})")
        for key, pred in (("opredelyaetsya_stoimost_remonta", "opredelyaetsya_stoimost_vosstanovitelnogo_remonta"),
                          ("dokumenty_o_dtp", "dokumenty_o_povrezhdeniyakh_v_dtp_predstavleny")):
            if i.get(key) is True:
                a(f"{pred}({E['r']})")
            elif i.get(key) is False:
                a(f"not {pred}({E['r']})")
        checks += truth_expect(f"osmotr_vozmozhen({E['r']})", x["vozmozhen"])
        checks += truth_expect(f"osmotr_dopustim({E['r']})", x["dopustim"])
    elif scope == "SrokiPunkta3":
        a(f"poterpevshiy_po_raschetu({E['r']}, {E['p']})")
        if i.get("uproshchennoe_oformlenie"):
            a(f"uproshchennoe_oformlenie_proisshestviya({E['r']})")
        if i.get("otchet_poluchen"):
            a(f"otchet_poluchen_poterpevshim({E['r']}, @{i['otchet_poluchen']})")
        if i.get("otmetka_nesoglasiya_poluchena"):
            a(f"otmetka_nesoglasiya_poluchena_strakhovshchikom({E['r']}, @{i['otmetka_nesoglasiya_poluchena']})")
        if i.get("osmotr_osushchestvlen"):
            a(f"osmotr_osushchestvlen_strakhovshchikom({E['r']}, @{i['osmotr_osushchestvlen']})")
        if i.get("otchet_predostavlen") is True:
            a(f"otchet_predostavlen_poterpevshemu({E['r']})")
        elif i.get("otchet_predostavlen") is False:
            a(f"not otchet_predostavlen_poterpevshemu({E['r']})")
        if i.get("den_rassmotreniya"):
            a(f"den_rassmotreniya_dela({E['r']}, @{i['den_rassmotreniya']})")
        date = lambda v: f"@{v}"  # noqa: E731
        checks += value_expect("day", "Date", f"predel_otmetki_poterpevshego({E['r']}, {{v}})", x["predel_otmetki"], date)
        checks += value_expect("day", "Date", f"predel_otveta_strakhovshchika({E['r']}, {{v}})", x["predel_otveta"], date)
        checks += value_expect("day", "Date", f"predel_predostavleniya_otcheta({E['r']}, {{v}})", x["predel_otcheta"], date)
        checks += truth_expect(f"otchet_ne_predostavlen_v_srok({E['r']})", x["otchet_ne_v_srok"])
        checks += truth_expect(f"pravo_na_vyplatu_po_punktu_3_1_stati_22_zakona({E['p']}, {E['r']})", x["pravo_na_vyplatu"])
    elif scope == "ItogovayaVelichina":
        if i.get("summa") is not None:
            a(f"itogovaya_stoimost_v_tenge({E['o']}, {money(i['summa'])})")
        if i.get("rasshifrovana_propisyu"):
            a(f'otchet_summa_propisyu({E["o"]}, "образец")')
        checks += truth_expect(f"otchet_soderzhit_itogovuyu_velichinu({E['o']})", x["nadlezhashche"])
    else:
        raise SystemExit(f"unknown scope {scope}")
    calendar = scope == "SrokiPunkta3"
    body = "".join(f'        assert {fact} {{ id "{case["id"]}-a{n}"; origin case_input; }}\n' for n, fact in enumerate(facts))
    text = (f"// {case['id']} — {case['source']}: {case['rationale']}\n"
            f'test "urn:query:vred-parity:{case["id"]}" {{\n    given {{\n'
            + (CONTEXT_CAL if calendar else CONTEXT_NO_CAL) + body + "    }\n" + checks + "}\n\n")
    return text, calendar


def render_suites(cases: dict) -> dict[str, str]:
    plain, cal = HEADER.format(version="0.2"), HEADER.format(version="0.1") + PROFILE
    for case in cases["cases"]:
        text, calendar = lawtest_case(case)
        if calendar:
            cal += text
        else:
            plain += text
    return {"parity.lawtest": plain, "parity-sroki.lawtest": cal}


def emit(check: bool) -> int:
    rendered = render_suites(load_cases())
    PARITY_DIR.mkdir(exist_ok=True)
    stale = []
    for name, text in rendered.items():
        path = PARITY_DIR / name
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            path.write_text(text, encoding="utf-8")
            print(f"emitted {path.relative_to(ROOT)}")
    if check and stale:
        print(f"parity suites stale: {stale}; run --emit", file=sys.stderr)
        return 1
    if check:
        print("parity suites: up to date")
    return 0


# --------------------------------------------------------------------------
# Catala
# --------------------------------------------------------------------------
def clerk_binary() -> str:
    found = shutil.which("clerk")
    if found:
        return found
    for candidate in sorted(Path.home().glob(".opam/*/bin/clerk")):
        return str(candidate)
    raise SystemExit("clerk (Catala 1.2) not found: opam install catala.1.2.0")


_PROJECT: Path | None = None


def clerk_project() -> Path:
    """Temporary copy of the model with its OWN `_build` next to it.

    `clerk` keeps the standard library in `_build/libcatala` RELATIVE to the
    project and re-checks it on every run when `CLERK_BUILD_DIR` is moved
    out: a 09.09.2026 measurement showed 2.0-3.7s against 0.04s for a warm
    in-project `_build`, i.e. fifty times more expensive for nothing.
    The package directory stays clean either way: the copy lives in the
    process's temporary directory.
    """
    global _PROJECT
    if _PROJECT is None:
        _PROJECT = Path(tempfile.mkdtemp(prefix="vred-ts-catala-"))
        shutil.copyfile(MODEL, _PROJECT / MODEL.name)
    return _PROJECT


def clerk_env() -> dict:
    """PATH with the opam switch's directory: building the stdlib needs `ocamlc`."""
    binary = Path(clerk_binary()).resolve()
    return dict(os.environ, PATH=f"{binary.parent}{os.pathsep}{os.environ.get('PATH', '')}")


def run_catala(scope: str, inputs: dict, calendar: dict) -> tuple[dict | None, str]:
    payload = dict(inputs)
    if scope == "SrokiPunkta3":
        payload["kalendar"] = calendar
    project = clerk_project()
    result = subprocess.run([clerk_binary(), "run", MODEL.name, f"--scope={scope}", "--input", json.dumps(payload),
                             "-F", "json", "--color=never"], capture_output=True, text=True,
                            cwd=project, env=clerk_env())
    if result.returncode != 0:
        return None, (result.stdout + result.stderr).strip()
    return json.loads(result.stdout), ""


def normalize(value):
    if isinstance(value, float):
        return Decimal(str(value)).normalize()
    if isinstance(value, (int,)) and not isinstance(value, bool):
        return Decimal(value).normalize()
    return value


def compare_outputs(expected: dict, actual: dict | None) -> list[str]:
    problems = []
    for key, want in expected.items():
        got = None if actual is None else actual.get(key)
        if normalize(want) != normalize(got):
            problems.append(f"{key}: expected {want!r}, Catala gave {got!r}")
    if actual is not None:
        for key in actual:
            if key not in expected:
                problems.append(f"{key}: extra Catala output {actual[key]!r}")
    return problems


def check_catala(verbose: bool) -> int:
    cases = load_cases()
    calendar = load_calendar(cases)
    failures = 0
    for case in cases["cases"]:
        actual, error = run_catala(case["scope"], case["inputs"], calendar)
        if error:
            failures += 1
            print(f"FAIL {case['id']} ({case['scope']}): Catala failed — {error[:400]}")
            continue
        problems = compare_outputs(case["expected"], actual)
        if problems:
            failures += 1
            print(f"FAIL {case['id']} ({case['scope']}): " + "; ".join(problems))
        elif verbose:
            print(f"PASS {case['id']} ({case['scope']}): {actual}")
    total = len(cases["cases"])
    print(f"catala: {total - failures}/{total} cases matched the cases.json expectations")
    return 1 if failures else 0


# --------------------------------------------------------------------------
# lawc + lawref via the profile (private snapshot)
# --------------------------------------------------------------------------
def run_engines(python: str) -> int:
    if emit(check=True):
        return 1
    with tempfile.TemporaryDirectory(prefix="vred-ts-parity-") as tmp:
        snapshot = Path(tmp) / "snapshot"
        build = subprocess.run([python, str(ROOT / "verify/ci/tools/work_profile.py"), "--build-only", "--output", str(snapshot)],
                               cwd=ROOT)
        if build.returncode:
            return build.returncode
        env = dict(os.environ, LAW_WORK_PROFILE_STATE=str(snapshot / "state.json"), PYTHONUNBUFFERED="1")
        gate = subprocess.run([python, str(ROOT / "verify/ci/gates/compiler/check_lawtest_suites.py"), "--only", FAMILY],
                              cwd=ROOT, env=env)
        return gate.returncode


# --------------------------------------------------------------------------
# Properties: random cases, the Python reference, Catala and lawc
# --------------------------------------------------------------------------
def random_case(rng: random.Random, scope: str) -> dict:
    def maybe(value, p=0.85):
        return value if rng.random() < p else None
    if scope == "Gibel":
        market = rng.choice([0, 1, rng.randint(1, 10_000_000), rng.randint(1, 10_000_000)])
        costs_choice = rng.random()
        costs = (market * 4 // 5 if costs_choice < 0.25 else market * 4 // 5 + 1 if costs_choice < 0.5
                 else rng.randint(0, 10_000_000))
        i = {"tekhnicheski_nevozmozhno": rng.random() < 0.3}
        if maybe(True) is not None:
            i["ozhidaemye_raskhody"] = costs
        if maybe(True) is not None:
            i["rynochnaya_stoimost"] = market
        per = rng.choice([True, False, None])
        if per is not None:
            i["ostatki_peredany"] = per
        if maybe(True, 0.7) is not None:
            i["stoimost_godnykh_ostatkov"] = rng.randint(0, 2_000_000)
        return i
    if scope == "StoimostDetali":
        i = {"podlezhit_zamene": rng.random() < 0.85, "ne_podlezhit_tekhosmotru": rng.random() < 0.6,
             "na_garantiynom_obsluzhivanii": rng.random() < 0.6, "ranee_ne_povrezhdalas": rng.random() < 0.85,
             "ne_podvergalas_remontu": rng.random() < 0.85}
        owner = rng.choice(["FizicheskoeLitso", "YuridicheskoeLitso", None])
        if owner:
            i["vladelets"] = owner
        km = rng.choice([15000, 15001, 20000, 20001, rng.randint(0, 40000), None])
        if km is not None:
            i["srednegodovoy_probeg_km"] = km
        if maybe(True) is not None:
            i["stoimost_novoy"] = rng.randint(1, 1_000_000)
        if maybe(True) is not None:
            i["stoimost_s_uchetom_iznosa"] = rng.randint(1, 1_000_000)
        return i
    if scope == "VyborOtsenshchikov":
        n = rng.choice([0, 1, 2, 3, rng.randint(0, 10), None])
        return {} if n is None else {"predlozheno": n}
    if scope == "SrokiPunkta3":
        def day():
            return (dt.date(2026, 1, 1) + dt.timedelta(days=rng.randint(-3, 370))).isoformat()
        i = {"uproshchennoe_oformlenie": rng.random() < 0.15}
        for key, p in (("otchet_poluchen", 0.6), ("otmetka_nesoglasiya_poluchena", 0.4), ("osmotr_osushchestvlen", 0.7)):
            if rng.random() < p:
                i[key] = day()
        pred = rng.choice([True, False, None])
        if pred is not None:
            i["otchet_predostavlen"] = pred
        if rng.random() < 0.6:
            i["den_rassmotreniya"] = day()
        return i
    raise SystemExit(scope)


def run_property(count: int, seed: int, python: str, with_lawc: bool) -> int:
    cases = load_cases()
    calendar = load_calendar(cases)
    ref = Reference(calendar)
    rng = random.Random(seed)
    scopes = ["Gibel", "StoimostDetali", "VyborOtsenshchikov", "SrokiPunkta3"]
    generated = []
    for n in range(count):
        scope = scopes[n % len(scopes)]
        inputs = random_case(rng, scope)
        generated.append({"id": f"P{n:04d}", "scope": scope, "source": "property", "inputs": inputs,
                          "expected": ref.compute(scope, inputs), "rationale": f"seed={seed}"})
    failures = 0
    for case in generated:
        actual, error = run_catala(case["scope"], case["inputs"], calendar)
        problems = [error[:300]] if error else compare_outputs(case["expected"], actual)
        if problems:
            failures += 1
            print(f"FAIL catala {case['id']} {case['scope']} {json.dumps(case['inputs'])}: {'; '.join(problems)}")
    print(f"property/catala: {count - failures}/{count} random cases matched the Python reference (seed {seed})")
    if not with_lawc:
        return 1 if failures else 0
    # lawc on the same cases: generated tests in a private profile snapshot.
    rendered = render_suites({"cases": generated})
    with tempfile.TemporaryDirectory(prefix="vred-ts-property-") as tmp:
        snapshot = Path(tmp) / "snapshot"
        if subprocess.run([python, str(ROOT / "verify/ci/tools/work_profile.py"), "--build-only", "--output", str(snapshot)],
                          cwd=ROOT, capture_output=True).returncode:
            print("failed to build a private profile snapshot", file=sys.stderr)
            return 1
        sys.path[:0] = [str(ROOT / "corpus"), str(ROOT / "corpus/lib"), str(ROOT / "engines/lawref")]
        os.environ["LAW_WORK_PROFILE_STATE"] = str(snapshot / "state.json")
        from lawtests.run import world_json, context_json, LAWCLI  # noqa: E402
        # The §85 calendar dataset is looked up upward from the test file along artifact:corpus/clir/…
        dataset = ROOT / cases["calendar_dataset"]
        (Path(tmp) / "corpus/clir").mkdir(parents=True)
        shutil.copyfile(dataset, Path(tmp) / "corpus/clir" / dataset.name)
        lawc_failures = 0
        for name, text in rendered.items():
            path = Path(tmp) / name
            path.write_text(text, encoding="utf-8")
            world = ["kz.corpus.vred_ts"] + (["kz.corpus.clir.official_calendar"] if "sroki" in name else [])
            program = Path(tmp) / f"{name}.world.json"
            program.write_text(world_json(tuple(world)), encoding="utf-8")
            listing = Path(tmp) / f"{name}.list.json"
            listing.write_text(json.dumps([str(path)]), encoding="utf-8")
            imports = Path(tmp) / f"{name}.imports.json"
            imports.write_text(context_json(tuple(world)), encoding="utf-8")
            result = subprocess.run([str(LAWCLI), "test", str(listing), "--lawtest-list", "--program", str(program),
                                     "--imports", str(imports), "--json"], capture_output=True, text=True)
            try:
                report = json.loads(result.stdout)
                report["tests"]
            except (ValueError, KeyError):
                print(f"lawc test did not produce a suite report: {(result.stdout + result.stderr)[-1200:]}", file=sys.stderr)
                return 1
            for item in report["tests"]:
                if not item["passed"]:
                    lawc_failures += 1
                    print(f"FAIL lawc {item['title']}: {'; '.join(item['failures'])}")
        print(f"property/lawc: {count - lawc_failures}/{count} random cases matched the Python reference (seed {seed})")
    return 1 if (failures or lawc_failures) else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--catala", action="store_true")
    parser.add_argument("--engines", action="store_true")
    parser.add_argument("--property", type=int, metavar="N")
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--no-lawc", action="store_true", help="in --property, only Catala against the reference")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--python", default=os.environ.get("LAW_WORK_PYTHON") or (
        str(ROOT / ".venv-work-profile/bin/python") if (ROOT / ".venv-work-profile/bin/python").exists() else sys.executable))
    args = parser.parse_args()
    rc = 0
    if args.emit:
        rc |= emit(check=False)
    if args.check or args.all:
        rc |= emit(check=True)
    if args.catala or args.all:
        rc |= check_catala(args.verbose)
    if args.engines or args.all:
        rc |= run_engines(args.python)
    if args.property:
        rc |= run_property(args.property, args.seed, args.python, not args.no_lawc)
    if not any((args.emit, args.check, args.catala, args.engines, args.property, args.all)):
        parser.print_help()
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
